package com.savaz.DeliveryService.db;

public enum City {
    KIEV,KHARKIV,ODESA,DONETSK,DNIPRO,ZAPORIZHIA,LVIV,LUHANSK,VINNITSIA,
    LUTSK,ZHITOMIR,RIVNE,SUMY,TERNOPIL,UZHHOROD,IVANO_FRANKIVSK,KROPYVNITSKII,
    MYKOLAYIV,POLTAVA,KHERSON,KHMELNITSKII,CHERKASY,CHERNIVTSI,CHERNIHIV
}
